// src/routes/widget.ts
// Serves the built widget.js browser script.
// The widget content is generated by scripts/build-widget.js (npm run build:widget)

// This import is generated by the build step. If missing, run: npm run build:widget
import { WIDGET_JS } from "../generated/widget-content";

export function handleWidget(): Response {
  if (!WIDGET_JS) {
    return new Response("// Reviews Widget — build not found. Run: npm run build:widget", {
      status: 503,
      headers: { "Content-Type": "application/javascript" },
    });
  }

  return new Response(WIDGET_JS, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
