// scripts/build-widget.js
// 1. Concatenates all widget/browser JS files into assets/widget.js
// 2. Generates src/generated/widget-content.ts — a TS module the Worker can import.

var fs = require("fs");
var path = require("path");

var ROOT = path.join(__dirname, "..");
var WIDGET_SRC = path.join(ROOT, "src", "widget");
var JS_OUTPUT = path.join(ROOT, "assets", "widget.js");
var TS_OUTPUT = path.join(ROOT, "src", "generated", "widget-content.ts");

var files = [
  "config.js",
  "api-client.js",
  "render.js",
  "themes/tokens.js",
  "components/review-card.js",
  "components/modal.js",
  "components/cta-button.js",
  "modes/inline-grid.js",
  "modes/inline-carousel.js",
  "modes/flyout.js",
  "index.js"
];

function build() {
  var jsParts = [];
  jsParts.push("// Reviews Widget v1.0.0");
  jsParts.push("// https://reviews.marketinghero.net");
  jsParts.push("");

  for (var i = 0; i < files.length; i++) {
    var file = files[i];
    var filePath = path.join(WIDGET_SRC, file);
    if (!fs.existsSync(filePath)) {
      console.warn("[build-widget] Missing: " + file + " — skipping");
      continue;
    }
    var content = fs.readFileSync(filePath, "utf-8");
    jsParts.push("// --- " + file + " ---");
    jsParts.push(content);
    jsParts.push("");
  }

  var widgetJS = jsParts.join("\n");

  // Write plain JS asset
  fs.mkdirSync(path.dirname(JS_OUTPUT), { recursive: true });
  fs.writeFileSync(JS_OUTPUT, widgetJS, "utf-8");

  // Write TypeScript module for Worker import
  // Escape backticks and $ for template literal
  var escaped = widgetJS
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$");

  var tsContent = [
    "// GENERATED BY scripts/build-widget.js — DO NOT EDIT",
    "// Run `npm run build:widget` to regenerate",
    "",
    "export const WIDGET_JS: string = `" + escaped + "`;",
    ""
  ].join("\n");

  fs.mkdirSync(path.dirname(TS_OUTPUT), { recursive: true });
  fs.writeFileSync(TS_OUTPUT, tsContent, "utf-8");

  console.log("[widget] Built " + JS_OUTPUT + " (" + widgetJS.length + " bytes)");
  console.log("[widget] Generated " + TS_OUTPUT);
}

build();
